language: cpp
sudo: false
compiler:
  - clang
  - gcc

os: linux
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - g++
      - clang
      - cmake

script:
  - gcc -v && g++ -v
  - clang -v
  - cmake --version

  - mkdir build
  - cd build
  - cmake .. && make
  - ./PathTracingTest
