language: cpp
sudo: false
compiler:
  - clang
  - gcc

os: linux
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

script:
  - gcc -v && g++ -v && cmake --version

  - mkdir build
  - cd build
  - cmake .. && make
  - ./PathTracingTest
