# version string format -- This will be overwritten later anyway
version: "{build}"

environment:
  MSVC_DEFAULT_OPTIONS: ON

os:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input
  # Set build version to git commit-hash
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

# This allows us to pass %PLATFORM% to CMake -A.
platform:
  - x64

# build Configurations, i.e. Debug, Release, etc.
configuration:
  - Release

install:
  - cmmd: echo "Downloading conan..."
  - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmmd: pip.exe install conan
  - cmmd: conan user # Create the conan data directory
  - cmmd: conan --version

#Cmake will autodetect the compiler, but we set the arch
before_build:
  - mkdir Build
  - cd Build
  - conan install ..
  - cd ..
  - cmake -H. -BBuild -A%PLATFORM%

# build with MSBuild
build:
  project: Build\BolderRenderEngine.sln   # path to Visual Studio solution or project
  parallel: true                        # enable MSBuild parallel builds
  verbosity: normal                     # MSBuild verbosity level {quiet|minimal|normal|detailed}

test_script:
  - cd Build
  - ctest -V -j 2 -C %CONFIGURATION%

